favicon: null
name: whiteorchid
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.311828
  brandStrength: 1
  lightness: 0.5483871
  brandColors:
    - '#040404'
    - '#B1CBDC'
    - '#2DA2C6'
    - '#F8A468'
    - '#B94E45'
  rhythmicContrast: 0.1877057
typography_spectrum: 0.8755876796785742
layout_spectrum: 0.189675732748583
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
